env:
  browser: true
  es6: true
  webextensions: true

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2017
  sourceType: module

extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:jsx-a11y/recommended

globals:
  ClassicEditor: false
  Jose: false
  JoseJWE: false
  Kinto: false
  KintoClient: false
  Quill: false
  TestPilotGA: false
  customizeEditor: false
  formatFooterTime: false
  fxaCryptoRelier: false
  fxaFetchProfile: false
  fxaRenewCredential: false
  getPadStats: false
  localizeEditorButtons: false
  migrationCheck: false
  retrieveNote: false
  setAnimation: false

plugins:
  - jsx-a11y
  - react

root: true

rules:
  eqeqeq: error
  linebreak-style: [error, unix]
  no-console: warn
  no-var: error
  prefer-const: error
  quotes: [error, single]
  semi: [error, always]
