language: node_js
addons:
  firefox: latest
node_js:
  - "6"

matrix:
  include:
    - script: npm run test
      env:
        global:
          - FIREFOX_BINARY: firefox
      before_install:
         - export DISPLAY=:99.0
         - sh -e /etc/init.d/xvfb start
         - sleep 3
    - script: npm run build-ck
      env: BUILD_CK
    - script: npm run build
      env: BUILD_NOTES
    - script: npm run lint
      env: LINT
