language: node_js
addons:
  firefox: latest
node_js:
  - "6"
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
script:
  - npm run test
env:
  global:
    - FIREFOX_BINARY: firefox

matrix:
  include:
    - script: npm run build-ck
      env: BUILD_CK
      before_install:
    - script: npm run build
      env: BUILD_NOTES
      before_install:
    - script: npm run lint
      env: LINT
      before_script: npm run build
      before_install:
